#node.id=3
#process.roles=broker,controller
#controller.quorum.voters=1@kafka1:29092,2@kafka2:29093,3@kafka3:29094

#listeners=INTERNAL://kafka3:19094,EXTERNAL://0.0.0.0:9094,CONTROLLER://kafka3:29094
#advertised.listeners=INTERNAL://kafka3:19094,EXTERNAL://localhost:9094
#listener.security.protocol.map=INTERNAL:SSL,EXTERNAL:SSL,CONTROLLER:PLAINTEXT
#inter.broker.listener.name=INTERNAL
#controller.listener.names=CONTROLLER
#security.inter.broker.protocol=SSL

# SSL настройки
ssl.keystore.location=/etc/kafka/secrets/kafka3.keystore.jks
ssl.keystore.password=Password1_
ssl.key.password=Password1_
ssl.truststore.location=/etc/kafka/secrets/kafka3.truststore.jks
ssl.truststore.password=Password1_
ssl.client.auth=requested
ssl.endpoint.identification.algorithm=

# Replication факторы
#offsets.topic.replication.factor=3
#transaction.state.log.replication.factor=3
#transaction.state.log.min.isr=2
#default.replication.factor=3
#min.insync.replicas=2
#auto.create.topics.enable=false
