services:
  kafka1:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092"
      - "9095:9095"
    environment:
      CLUSTER_ID: fv1Ktv_cSOy96fbDcPz_rg
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:29092,2@kafka2:29093,3@kafka3:29094
      KAFKA_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka1:29092,SASL_PLAINTEXT://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://localhost:9092,SASL_PLAINTEXT://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:SASL_SSL,CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka1.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: Password1_
      KAFKA_SSL_KEY_PASSWORD: Password1_
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: Password1_
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      #KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      #KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SSL
      
      
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"
      
    networks:
      - kafka-network
    volumes:
      - ./ssl/kafka1:/etc/kafka/secrets
      - ./kafka_server_jaas.conf:/etc/kafka/secrets/kafka_server_jaas.conf

  kafka2:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka2
    hostname: kafka2
    ports:
      - "9093:9093"
    environment:
      CLUSTER_ID: fv1Ktv_cSOy96fbDcPz_rg
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:29092,2@kafka2:29093,3@kafka3:29094
      KAFKA_LISTENERS: INTERNAL://kafka2:19093,EXTERNAL://0.0.0.0:9093,CONTROLLER://kafka2:29093,SASL_PLAINTEXT://0.0.0.0:9096
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:19093,EXTERNAL://localhost:9093,SASL_PLAINTEXT://localhost:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:SASL_SSL,CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka2.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: Password1_
      KAFKA_SSL_KEY_PASSWORD: Password1_
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka2.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: Password1_
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      #KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      #KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SSL
      
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"
    networks:
      - kafka-network
    volumes:
      - ./ssl/kafka2:/etc/kafka/secrets
      - ./kafka_server_jaas.conf:/etc/kafka/secrets/kafka_server_jaas.conf

  kafka3:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka3
    hostname: kafka3
    ports:
      - "9094:9094"
    environment:
      CLUSTER_ID: fv1Ktv_cSOy96fbDcPz_rg
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:29092,2@kafka2:29093,3@kafka3:29094
      KAFKA_LISTENERS: INTERNAL://kafka3:19094,EXTERNAL://0.0.0.0:9094,CONTROLLER://kafka3:29094,SASL_PLAINTEXT://0.0.0.0:9097
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:19094,EXTERNAL://localhost:9094,SASL_PLAINTEXT://localhost:9097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:SASL_SSL,CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka3.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: Password1_
      KAFKA_SSL_KEY_PASSWORD: Password1_
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka3.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: Password1_
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      #KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      #KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SSL
      
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"

    networks:
      - kafka-network
    volumes:
      - ./ssl/kafka3:/etc/kafka/secrets
      - ./kafka_server_jaas.conf:/etc/kafka/secrets/kafka_server_jaas.conf

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8080:8080"
    networks:
      - kafka-network
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:19092,kafka2:19093,kafka3:19094
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/ca-truststore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: Password1_
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
    volumes:
      - ./ssl/ca-truststore.jks:/etc/kafka/secrets/ca-truststore.jks
      - ./ssl/ca-key:/etc/kafka/secrets/ca-key
      - ./ssl/ca-crt:/etc/kafka/secrets/ca-crt
networks:
  kafka-network:
    driver: bridge
