listeners=SSL://localhost:9092
ssl.keystore.location=/opt/kafka/private/kafka1.keystore.jks
ssl.keystore.password=Password1_
ssl.key.password=Password1_
ssl.truststore.location=/opt/kafka/private/kafka1.truststore.jks
ssl.truststore.password=Password1_
security.inter.broker.protocol=SSL
ssl.client.auth=requested
ssl.endpoint.identification.algorithm=
