ssl.keystore.location=/etc/kafka/secrets/kafka1.keystore.jks
ssl.keystore.password=Password1_
ssl.key.password=Password1_
ssl.truststore.location=/etc/kafka/secrets/kafka1.truststore.jks
ssl.truststore.password=Password1_
ssl.client.auth=requested
ssl.endpoint.identification.algorithm=


